### ISSUE TITLE
felpakolnám a képeket

### ISSUE THREAD

**Issue by ghost** [elyth91/WPF-CardGameDuels---RFT#2]
Csak abszolút nem tudom, hogyan pakoljam fel a laptomomra a kis cuccot.
elvesztettem a jegyzetemet erről :(

**Comment by ghost** [comment]
oké, most úgy tűnik, húz le valamit, telepítés perceken belül (ha a wifi istenei is így gondolják)

**Comment by ghost** [comment]
okéééé, most már működik, csak még bizonytalan ez az egész. megpróbálok valamit felpakolni :3

**Comment by ghost** [comment]
Niki, már felraktad a képeket? :(

**Comment by elyth91** [comment]
Már fel, azt kéne elérni hogy, a kliens alkalmazáson belül legyenek feltöltve
A projekthez add hozzá (Add new existing item) a képeket és helyezd el pictureboxokban a gamefield ablakon
Röviden :D

**Comment by ghost** [comment]
aha, náam semmi ilyen nincs :O

**Comment by ghost** [comment]
![wutwut](https://cloud.githubusercontent.com/assets/15088477/11817102/bc12ad50-a353-11e5-8516-ee5e430707e0.jpg)
