### ISSUE TITLE
Miért nem megy fel??

### ISSUE THREAD

**Issue by ghost** [elyth91/WPF-CardGameDuels---RFT#3]
Találtam néhány file-t felpakoln, és nem találom az opciót hozzá. Csak klónozni tudok. -.-"

**Comment by elyth91** [comment]
ha még nincsenek meg a fileok csak klónozni tudsz
és a klónozott mappába tudsz pullozni

**Comment by ghost** [comment]
a klónozás a legelején megvolt

**Comment by ghost** [comment]
most mintha valamit csinált volna
lát valaki valami újat?

**Comment by ghost** [comment]
elvileg két rft file baba
